### ISSUE TITLE
workspace back_and_forth support

### ISSUE THREAD

**Issue by tbrodbeck** [justbuchanan/i3scripts#23]
Hey it would be great if it still would be possible to work with the `workspace back_and_forth` command. Since it goes to the last workspace remembered by the exact name, it often opens a new workspace if the old one was renamed in the meantime. 
You can reproduce this when having a workspace open with 2 containers and you move one of them to another workspace. When using `workspace back_and_forth`  it will look for the workspace with the two containers in the name (but it does not exist anymore, since one container was moved away) and it will open a new window instead (with duplicate numbers).

**Comment by tbrodbeck** [comment]
I actually also put a ticket up in the i3 repo. (https://github.com/i3/i3/issues/3694) so maybe there will be a fix coming. Still a workaround would be nice

**Comment by justbuchanan** [comment]
@tbrodbeck thanks for reporting this. I read the responses on the i3 issue you opened and I think their suggestion of having `workspace back_and_forth` rely on container id instead of name is probably the best solution. It would be difficult to workaround the issue from these python scripts since there isn't really a way to maintain consistent workspace names and also "rename" them to include icons.

Closing this in favor of i3/i3#3694, but feel free to reopen if you think there's a reasonable workaround to be implemented in this repo.
